# blog/tags.yml
git:
  label: Git
  permalink: /tags/git
workflow:
  label: Workflow
  permalink: /tags/workflow
buenas-practicas:
  label: Buenas Prácticas
  permalink: /tags/buenas-practicas
nginx:
  label: Nginx
  permalink: /tags/nginx
redes:
  label: Redes
  permalink: /tags/redes
database:
  label: Database
  permalink: /tags/database
liquibase:
  label: Liquibase
  permalink: /tags/liquibase
devops:
  label: DevOps
  permalink: /tags/devops
databasedevops:
  label: Database DevOps
  permalink: /tags/databasedevops
automation:
  label: Automation
  permalink: /tags/automation
vagrant:
  label: Vagrant
  permalink: /tags/vagrant
linux:
  label: Linux
  permalink: /tags/linux
infrastructure:
  label: Infrastructure
  permalink: /tags/infrastructure
infraestructura:
  label: Infraestructura
  permalink: /tags/infraestructura
automatzacion:
  label: Automatización
  permalink: /tags/automatizacion
